### ISSUE TITLE
Support Query#count

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j-core#124]
Example: `query.match("(a:A {name: 'foo'})--(b:B)").count(:b)`

**Comment by subvertallchris** [comment]
Brian fixed this.

**Comment by dpisarewski** [comment]
Does it make sense to make arguments of the `count`method optional? I created the `kaminari-neo4j` gem  and had to access internals of `neo4j-core` to make it possible.

https://github.com/megorei/kaminari-neo4j/blob/d757ed35f0488bbf9a6ffb62550f50af690aee4a/lib/kaminari/neo4j/paginated.rb#L24

**Comment by cheerfulstoic** [comment]
In master, at least, the argument to `count` is optional and makes a `COUNT(*)` in the background
