### ISSUE TITLE
NameError: cannot link Java class org.neo4j.graphdb.DynamicLabeL

### ISSUE THREAD

**Issue by dsisnero** [neo4jrb/neo4j-core#160]
c:\Dominic\programming\jruby\rails\myapp>jruby bin\rails s
NameError: cannot link Java class org.neo4j.graphdb.DynamicLabel, probable missing dependency: org/neo4j/graphdb/DynamicLabel : Unsup
ported major.minor version 51.0
         for_name at org/jruby/javasupport/JavaClass.java:1286
  get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
    const_missing at file:/C:/Dominic/rubies/jruby-1.7.18/lib/jruby.jar!/jruby/java/java_package_module_template.rb:4
    EmbeddedLabel at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded/embedded_label.rb:6

         Embedded at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded/embedded_label.rb:3

            Neo4j at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded/embedded_label.rb:2

           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded/embedded_label.rb:1

          require at org/jruby/RubyKernel.java:1071
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded.rb:1
          require at org/jruby/RubyKernel.java:1071
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-embedded.rb:7
          require at org/jruby/RubyKernel.java:1071
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-core.rb:1
          require at org/jruby/RubyKernel.java:1071
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-core-4.0.0/lib/neo4j-core.rb:24
             each at org/jruby/RubyArray.java:1613
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-4.1.1/lib/neo4j.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/neo4j-4.1.1/lib/neo4j.rb:12
           (root) at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/bundler-1.7.12/lib/bundler/runtime.rb:1
          require at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/bundler-1.7.12/lib/bundler/runtime.rb:76
          require at org/jruby/RubyKernel.java:1071
          require at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/bundler-1.7.12/lib/bundler/runtime.rb:72
              tap at org/jruby/RubyKernel.java:1886
          require at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/bundler-1.7.12/lib/bundler/runtime.rb:61
          require at C:/Dominic/rubies/jruby-1.7.18/lib/ruby/gems/shared/gems/bundler-1.7.12/lib/bundler.rb:134
           (root) at c:/Dominic/programming/jruby/rails/myapp/config/application.rb:16
          require at org/jruby/RubyKernel.java:1071
           (root) at bin\rails:4

HERES MY JRUBY INFORMATION

c:\Dominic\programming\jruby\rails\myapp>jruby --version
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.6.0_45-b06 +jit [Windows 7-amd64]

c:\Dominic\programming\jruby\rails\myapp>bundle show
Gems included by the bundle:
  * actionmailer (4.2.0)
  * actionpack (4.2.0)
  * actionview (4.2.0)
  * active_attr (0.8.5)
  * activejob (4.2.0)
  * activemodel (4.2.0)
  * activerecord (4.2.0)
  * activesupport (4.2.0)
  * arel (6.0.0)
  * builder (3.2.2)
  * bundler (1.7.12)
  * coffee-rails (4.1.0)
  * coffee-script (2.3.0)
  * coffee-script-source (1.8.0)
  * erubis (2.7.0)
  * execjs (2.2.2)
  * faraday (0.9.1)
  * faraday_middleware (0.9.1)
  * globalid (0.3.0)
  * hike (1.2.3)
  * httparty (0.13.3)
  * httpclient (2.6.0.1)
  * i18n (0.7.0)
  * jbuilder (2.2.6)
  * jquery-rails (4.0.3)
  * json (1.8.2)
  * loofah (2.0.1)
  * mail (2.6.3)
  * mime-types (2.4.3)
  * minitest (5.5.1)
  * multi_json (1.10.1)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * neo4j (4.1.1)
  * neo4j-community (2.1.5)
  * neo4j-core (4.0.0)
  * net-http-persistent (2.9.4)
  * nokogiri (1.6.5)
  * orm_adapter (0.5.0)
  * os (0.9.6)
  * rack (1.6.0)
  * rack-test (0.6.3)
  * rails (4.2.0)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.5)
  * rails-html-sanitizer (1.0.1)
  * railties (4.2.0)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * sass (3.4.10)
  * sass-rails (5.0.1)
  * sdoc (0.4.1)
  * sprockets (2.12.3)
  * sprockets-rails (2.2.2)
  * therubyrhino (2.0.4)
  * therubyrhino_jar (1.7.4)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * tzinfo-data (1.2014.10)
  * uglifier (2.7.0)
  * zip (2.0.2)

**Comment by subvertallchris** [comment]
I'm afraid I'm not exactly sure how to go about troubleshooting this... I'll see if we can get help from someone who's done work with JRuby and Java dependencies. Are you able to do `jruby bin\bundle exec rails s`?

**Comment by subvertallchris** [comment]
Going to close this out since there hasn't been any more activity. I think it has to do with loading the Java dependency in Windows. If anyone else runs into this, please get in touch.
