### ISSUE TITLE
Can not execute a cypher query that does not return any result

### ISSUE THREAD

**Issue by drouchy** [neo4jrb/neo4j-core#180]
Hi,

I'm trying to delete some nodes & relationship with a cypher query, the the driver is raising an exception:

```
irb(main):001:0>  query = 'MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r'
=> "MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r"
irb(main):002:0> Neo4j::Session.query query
ArgumentError: wrong number of arguments (0 for 1)
from /opt/rubies/jruby-1.7.12/lib/ruby/gems/shared/bundler/gems/neo4j-core-9da01b97d2b3/lib/neo4j-embedded/cypher_response.rb:19:in `initialize'
```

I can successfully execute a query with a return clause.

Cheers,

David

**Comment by subvertallchris** [comment]
Looks like you have a typo in that second line.

**Comment by drouchy** [comment]
yes, sorry wrong copy & paste

I updated the comment

**Comment by subvertallchris** [comment]
What version of Neo4j-core are you using?

**Comment by drouchy** [comment]
the head of master

**Comment by subvertallchris** [comment]
I see what it is...

```
def initialize(source, query, unwrapped = nil)
        @source = source
        @struct = Struct.new(*source.columns.to_a.map(&:to_sym))
        @unread = true
        @query = query
        @unwrapped = unwrapped
      end
```

There are no columns in that response so it's returning nil. Let me see if I can patch that for you real quick...

**Comment by subvertallchris** [comment]
That fixes it. Tests pass locally but I need to let Travis give another OK before I merge. Running out to grab lunch, should be done when I get back.

**Comment by drouchy** [comment]
that's awesome

thanks
