### ISSUE TITLE
can't log into localhost without authorization header.

### ISSUE THREAD

**Issue by voodoologic** [neo4jrb/neo4j-core#182]
I just updated neo4j using brew.  

When trying to run my application (using neo4jrb 4.0.5) I got this error.

`handle_response_error': Expected response code 200 Error for request http://localhost:7474/db/data/, 401, 401 (Neo4j::Server::Resource::ServerException)

in a browser localhost:7474/db/data returns json:
    "message": "No authorization header supplied.",
    "code": "Neo.ClientError.Security.AuthorizationFailed"

**Comment by subvertallchris** [comment]
I'm guessing they just pushed Neo4j 2.2.0 to brew. Disable auth by editing the config file as described at http://neo4j.com/docs/stable/security-server.html#security-server-auth.

**Comment by voodoologic** [comment]
word.  Thanks for the quick response!

**Comment by cheerfulstoic** [comment]
Yup, looks like they did: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/neo4j.rb

**Comment by voodoologic** [comment]
http://localhost:7474/browser/ displays a default username and password (neo4j/neo4j).  For anyone else who has this problem, go there and you'll be able to set the username and password yourself for your system.

**Comment by cheerfulstoic** [comment]
Also, I believe that there's a `rake neo4j:change_password` rake task that you can use

**Comment by cheerfulstoic** [comment]
(from the gem)

**Comment by apogre** [comment]
+1

**Comment by cheerfulstoic** [comment]
I think this one is good
