### ISSUE TITLE
'load 'neo4j/tasks/neo4j_server.rake'' in the Rakefile doesn't work

### ISSUE THREAD

**Issue by samis** [neo4jrb/neo4j-core#194]
The documentation says to add 'load 'neo4j/tasks/neo4j_server.rake' to the Rakefile to get the neo4j tasks. This does not work, as rake reports the following error:
`LoadError: cannot load such file -- neo4j/tasks/neo4j_server.rake`

**Comment by cheerfulstoic** [comment]
FYI you should only do that if you're not using Rails.

If you're not using Rails, how are you including the gem?  That error makes me thing that the `neo4j-core` gem isn't in the load path.  Also, what version are you using?

**Comment by samis** [comment]
Oops. Adding the appropriate line 'require neo4j-core' to my Rakefile fixed this one. Chalk this up to me still learning about Ruby / Rake.

**Comment by cheerfulstoic** [comment]
Glad that it's fixed, though one thing I would also suggest is, if you're using bundler (that is, if you have a `Gemfile`) you should perhaps run `bundle exec rake` instead of just `rake`.  Bundle does all of the `require`s for you and makes sure that you're running in the right environment
