### ISSUE TITLE
broken links on doc

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j-core#199]
![image](https://cloud.githubusercontent.com/assets/3890316/7522264/57653ef8-f4f4-11e4-924a-8d4111259193.png)

The 2 links in the image are broken (404): they are still referencing Andreas pages on github.

**Comment by cheerfulstoic** [comment]
Thanks so much!  I've fixed these now (always nice to have easy things to fix ;)

Also FYI I've been working on some new docs on readthedocs.org because the wiki's becoming a bit harder to maintain.
