### ISSUE TITLE
crash calling Neo4j::Session.open

### ISSUE THREAD

**Issue by amxfonseca** [neo4jrb/neo4j-core#221]
Hello,

For the record I have no previous experience with ruby or neo4j. I just decided to learn a bit more about graph databases and I decided first to write some data migration scripts in ruby to have some real data to work with.

When I try to create a new session with:

 `Neo4j::Session.open(:server_db, basic_auth: { username: 'neo4j', password: 'password'})` 

I get the following stack trace:

```
/Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j-server/cypher_session.rb:61:in `extract_basic_auth': undefined method `URI' for Neo4j::Session available: [:server_db]:Class (NoMethodError)
	from /Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j-server/cypher_session.rb:46:in `open'
	from /Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j-server/cypher_session.rb:4:in `block in <module:Server>'
	from /Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j/session.rb:120:in `call'
	from /Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j/session.rb:120:in `create_session'
	from /Users/andre/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j/session.rb:105:in `open'
	from app.rb:7:in `<main>'
```

Like I said I rarely use ruby so I don't know what are the best practices but should't exist a `require 'uri'` line somewhere? Because if I require the "uri" module in my script then I don't get any error and everything works as expected, but it doesn't make any sense having to require it on my side of the code.

Am I doing something wrong? Should I require something extra apart from "neo4j-core" on my script?

**Comment by subvertallchris** [comment]
You're right, it doesn't make sense for you to have to require it. :-) The gem should do that on its own. Keep doing that for now and thanks for bringing it up, we'll patch this soon.

**Comment by amxfonseca** [comment]
Thanks for the quick reply. I confess that I looked through all the code in the Github repo and I didn't found any reference to 'uri', but since I don't use ruby as a daily language (like I use javascript for example) I didn't want to say anything that sounded stupid. 

In the latest commits for this repo there are some code with references to 'httparty' that was removed, and 'httparty' requires 'uri' for sure. But I just did a quick look on the commits, I don't know if that is really related with this bug because I didn't read all the code.

Appreciate your help and keep up with your nice work.

**Comment by cheerfulstoic** [comment]
Try `neo4j-core` 5.0.7 and see if that fixes your issue

**Comment by cheerfulstoic** [comment]
@amxfonseca Any luck?

**Comment by amxfonseca** [comment]
Sorry for the late reply,
Since I've moved to another country recently I didn't have almost any time to work again on the project. 
But it fixes the issue. Thanks for all the help and hard work. Sorry for keeping the ticket open for that long.

**Comment by cheerfulstoic** [comment]
No problem, thanks!
