### ISSUE TITLE
Multiple `merge` calls shouldn't be joined together with comma

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j-core#224]
`MERGE` doesn't seem to support that.  Instead it should probably be different `MERGE` statements.  This might also be true for `create`/`CREATE`

**Comment by alexshuhin** [comment]
:+1: same issue

**Comment by cheerfulstoic** [comment]
@alexshuhin What version are you using?  I think perhaps I fixed this a little while ago.  Probably in the 6.0.x releases...

**Comment by alexshuhin** [comment]
~> 5.0.0. Yep, i see fdc18a37204b81a609bc801ba7d10e0152586b77

**Comment by cheerfulstoic** [comment]
Great.  Are you able to update to 6.0.0?  Normally I was try backporting it, but I would say this counts as a breaking change.  6.0.0 isn't too much different that 5.0.0, so I'd definitely suggest trying it

**Comment by alexshuhin** [comment]
@cheerfulstoic i wonder, why i use exactly ~> 5.0.0, seems to be, there was some problems with neo4j version(2.2) or legacy rails (3.2) to bundle the edge version.
i'll try to update it again, and report you

**Comment by cheerfulstoic** [comment]
Cool, going to close for now, but happy to answer questions here or in chat: https://gitter.im/neo4jrb/neo4j

**Comment by alexshuhin** [comment]
@cheerfulstoic i have update to 6.0.1, but got an error:
```ruby
neo4j = Neo4j::Session.open :server_db,
  'http://localhost:7474',
  basic_auth: { username: 'neo4j', password: 'mypassword' }

neo4j.query.match('(a)').limit(10).return(:a).to_a
```
become
```
NameError: uninitialized constant Neo4j::Core::CypherSession
from /home/medium/.rvm/gems/ruby-2.1.5@right-choice/gems/neo4j-core-6.0.1/lib/neo4j-core/query.rb:235:in `response'
```

**Comment by cheerfulstoic** [comment]
Oh, gosh, I should fix that.  I'll take a stab at it after dinner, but for now if you do:

    require 'neo4j/core/cypher_session`

I think that will get you past it

Pro-tip: `neo4j.query.match(:a).` will automagically surround with parens in the query

**Comment by cheerfulstoic** [comment]
Ok, I think I've fixed this.  Heading off to bed for the night, but you should be able to fix this by changing your `Gemfile` to this, for the time being:

    gem 'neo4j-core', github: 'neo4jrb/neo4j-core', branch: '6.0.x'

Once the specs all pass I'll release a patch for the 6.0.x series.

**Comment by alexshuhin** [comment]
cool! works fine
i'll return to 5.x version for now, waiting for 6.0.3

**Comment by cheerfulstoic** [comment]
Thanks for reminding me!  6.0.3 is out now
