### ISSUE TITLE
LoadError: cannot load such file -- neo4j/tasks/neo4j_server.rake

### ISSUE THREAD

**Issue by rawongithub** [neo4jrb/neo4j-core#256]
Obsolete wiki.
The content of the Rakefile should be:
load 'neo4j/rake_tasks/neo4j_server.rake'

**Comment by cheerfulstoic** [comment]
Thanks for finding this!  I think I might have fixed this from somebody else's report.  Was this the wiki page/section?

https://github.com/neo4jrb/neo4j-core/wiki#usage-from-neo4j-server

**Comment by rawongithub** [comment]
Yes it is in the "Usage from Neo4j Server" section.

**Comment by cheerfulstoic** [comment]
Oh, weird, I thought I had fixed it, but it looks like it wasn't fixed.  Fixed now, thanks so much!
