### ISSUE TITLE
Is there an ideal way to reuse the credentials from neo4j.yml?

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j-core#278]
I want to run a raw neo4j-core query along side some neo4jrb code, and so would like to reuse the config from `neo4j.yml`.
Is there an ideal way to do this?

Just checking in before coding it to parse the file and check for environment.

### Runtime information:

Neo4j database version:
`neo4j` gem version: `8.0.5`
`neo4j-core` gem version: `7.0.3`

**Comment by cheerfulstoic** [comment]
There is a `Neo4j::ActiveBase` module now with version 8.0 of the `neo4j` gem.  With that there are a few useful methods which encapsulate the current session:

```ruby
Neo4j::ActiveBase.new_query # Get a `Query` object
Neo4j::ActiveBase.run_transaction { <stuff in the block }
Neo4j::ActiveBase.query("MATCH (n) RETURN n")
Neo4j::ActiveBase.current_session
```

**Comment by Joshfindit** [comment]
Super awesome; this will make the app code so much easier!

**Comment by cheerfulstoic** [comment]
:+1:
