### ISSUE TITLE
Timeout is not configurable in Bolt driver

### ISSUE THREAD

**Issue by kamranjon** [neo4jrb/neo4j-core#286]
For the use case of importing large datasets, sometimes the server will take a longer time to respond, and because the timeout is not configurable on the bolt driver, it errors in these cases. 

### [If we could make it part of this options hash, we would be golden](https://github.com/neo4jrb/neo4j-core/blob/master/lib/neo4j/core/cypher_session/adaptors/bolt.rb#L23)

Thanks.

**Comment by cheerfulstoic** [comment]
Thanks @kamranjon !

I'm pretty constrained for time these days, but if you make a PR I would be happy to have a look over it

**Comment by cheerfulstoic** [comment]
Fixed it 7.2.4 and 8.0.1
